### ISSUE TITLE
suggestion for syntax

### ISSUE THREAD

**Issue by imanghafoori1** [barryvdh/laravel-form-bridge#1]
Compare these two syntax :

$form = app('form.factory')->create('form', $user)
        ->add('name', 'text')
        ->add('email', 'email')
#         ->add('save', 'submit', array('label' => 'Save user'));

  $form = app('form.factory')->create('form', $user)
        ->text('user_name')
        ->email(''email_address')
        ->submit('save', array('label' => 'Save user'));
# 

I think the second one read better, and IDE auto-completion is better for field types.
and it is simple to implement for you. it just requires some wrapper methods on current methods : 

public function text($name) {
   $this->add($name, 'text');
   return $this;
}

I hope it makes help.
I have created such a form builder for a zend based application.

**Comment by barryvdh** [comment]
Thanks! But I'm just wrapping the Symfony Form component, so it's their builder.

**Comment by imanghafoori1** [comment]
you mean that you want the final syntax to look the same as symfony form builder?

**Comment by imanghafoori1** [comment]
I think this one provides better syntax :
https://github.com/barryvdh/former

**Comment by remyflier** [comment]
Please keep it as close to the Symfony implementation as possible, First syntax clearly indicates that each form field should use a FormType. Especially using the namespace as type argument. That way there is no difference between native and custom formTypes.

**Comment by barryvdh** [comment]
Indeed, keep it close to Symfony.
