### ISSUE TITLE
Twig caching

### ISSUE THREAD

**Issue by kasparsklavins** [barryvdh/laravel-form-bridge#23]
Twig appears to be parsed on each request.
What would be the best way to go about implementing caching for twig templates?

**Comment by Upperfoot** [comment]
I think it may be wise to make use of https://github.com/rcrowe/TwigBridge as I believe that already implements caching. @barryvdh would it make sense to make use of the library above?

**Comment by barryvdh** [comment]
It already uses it when installed, but isn't required.
I coud add some useful cache features.

**Comment by barryvdh** [comment]
Better? https://github.com/barryvdh/laravel-form-bridge/commit/9064c1081d552e1e31db6e5cdda19a145a3e9195

**Comment by barryvdh** [comment]
Note that you can always use your own TwigEnvironment by registering the `\Twig_Environment` class yourself.

**Comment by Upperfoot** [comment]
Brilliant stuff Barry as always
