### ISSUE TITLE
Directives not work

### ISSUE THREAD

**Issue by alederzz** [barryvdh/laravel-form-bridge#28]
Hi, Barry.

The directives indicated in the readme file are not the correct ones, I think it is lacking to update.

```
@formStart($form)
@formWidget($form)
@formEnd($form)
```

It worked for me this way:
`@form_start($form)`

**Comment by barryvdh** [comment]
Tagged the latest version which has the updated names

**Comment by alederzz** [comment]
Thanks a lot Barry.
