### ISSUE TITLE
Nested form types validation

### ISSUE THREAD

**Issue by HoffmannAndras** [barryvdh/laravel-form-bridge#30]
Hey firstname,

Do you have any idea with nested form types validation with rules?

For instance:
```
class FooType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('custom', CustomType::class, $options);
        $builder->add('custom2', CustomType2::class, $options);
    ....
```
These types are always valid.
The rules are in the CustomType fields.
```
class CustomType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email', EmailType::class, [
                'rules' => [
                    'unique:user,email'
                ]
            ])

```

**Comment by bobmulder** [comment]
Wooh this is an old issue. However, I guess I got the same issue using the `CollectionType` in my parent form. Figured out that `constraints` (validation by Symfony Form itself) is working well. It seems that rules (implemented by @barryvdh ) don't work on child forms...

Any hint @barryvdh? I have no clue XD

Regards, Bob
