### ISSUE TITLE
Laravel 9 support?

### ISSUE THREAD

**Issue by sdousley** [barryvdh/laravel-form-bridge#44]
Is there any intention to update this package to support Laravel 9?

**Comment by barryvdh** [comment]
Can you try the latest dev-master / `0.6@dev` version?

**Comment by sdousley** [comment]
Thanks for the super quick response.  The 0.6 seems to require illuminate/support 8.x, so doesn't work.  I actually did some work on the package yesterday, and THINK I've got it to a working Laravel 9 set of packages, so I'll get that tested today, and look to get a PR over for it.

**Comment by barryvdh** [comment]
Oh oops, I meant to include 9. The test were running 9 already. Changed that. Let me know if something needs changes, because I only ran the testsuite, not a project itself.

**Comment by sdousley** [comment]
Well, I've not tested extensively within our system, but at least the first page I've loaded with a form on it works with the dev-master vesion, so I think that looks good to me

**Comment by barryvdh** [comment]
9 and 10 are now supported.
